name: Push Helm Chart to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Package Helm Chart
        run: |
          helm package manifests/testmod2

      - name: Push Helm Chart to GitHub Container Registry
        run: |
          export CHART_VERSION=$(cat manifests/testmod2/Chart.yaml | grep 'version:' | cut -d' ' -f2)
          export CHART_NAME=testmod2-${CHART_VERSION}.tgz
          export CR_PAT=${{ secrets.GHCR_PAT }}
          echo $CR_PAT | helm registry login ghcr.io -u ${{ github.repository_owner }} --password-stdin
          helm push $CHART_NAME oci://ghcr.io/${{ github.repository_owner }}/testmod2
        env:
          HELM_EXPERIMENTAL_OCI: "1"
